# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9645962aa422089b9bdcf61bbd07ae9a2592a546464793854c5fe62573aeeefa55458191e3061404f038db0a6a3b1246ca74b146485db697e8e6585be59701

test:
  secret_key_base: 6692d9eabde36cd09c064777468cc430e71e856cdd30ce4545bd11c2f69e76194015a7d9099b8bffba499b3a2f969512f4e3d1f54f56ad8e64e1858b4b32af3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
